In [1]:
import numpy as np

In [3]:
l=[10,20,30,40]
arr1=np.array(l)
arr1

array([10, 20, 30, 40])

In [5]:
len(arr1)

4

# Shape & Dimensions :

**ndim : n-dimensions**

In [9]:
arr1.ndim # one list 1 dimension

1

In [13]:
arr1.shape # Shape means matrix analysis

(4,)

In [21]:
l=[10,20,30,40]
arr1=np.array(l)
print(f'array :{arr1}')
print(f'array length : {len(arr1)}')
print(f'array dimension : {arr1.ndim}')
print(f'array shape : {arr1.shape}')

array :[10 20 30 40]
array length : 4
array dimension : 1
array shape : (4,)


In [25]:
l=[[10,20,30,40]]
arr2=np.array(l)
print(f'array :{arr2}')
print(f'array length : {len(arr2)}')
print(f'array dimension : {arr2.ndim}')
print(f'array shape : {arr2.shape}') # (rows,columns)

array :[[10 20 30 40]]
array length : 1
array dimension : 2
array shape : (1, 4)


In [31]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l=[l1,l2]
arr2=np.array(l)
print(f'array :\n{arr2}')
print(f'array length : {len(arr2)}')
print(f'array dimension : {arr2.ndim}')
print(f'array shape : {arr2.shape}') # (rows,columns)

array :
[[10 20 30 40]
 [ 1  2  3  4]]
array length : 2
array dimension : 2
array shape : (2, 4)


In [33]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=['A','B','C','D']
arr2=np.array([l1,l2,l3])
print(f'array :\n{arr2}')
print(f'array length : {len(arr2)}')
print(f'array dimension : {arr2.ndim}')
print(f'array shape : {arr2.shape}') # (rows,columns)

array :
[['10' '20' '30' '40']
 ['1' '2' '3' '4']
 ['A' 'B' 'C' 'D']]
array length : 3
array dimension : 2
array shape : (3, 4)


# 3-Dimensional :

In [36]:
l=[[ [10,20,30,40],
    [1,2,3,4],
    ['A','B','C','D']
    ]]
arr2=np.array([l1,l2,l3])
print(f'array :\n{arr2}')
print(f'array length : {len(arr2)}')
print(f'array dimension : {arr2.ndim}')
print(f'array shape : {arr2.shape}') # (rows,columns)

array :
[['10' '20' '30' '40']
 ['1' '2' '3' '4']
 ['A' 'B' 'C' 'D']]
array length : 3
array dimension : 2
array shape : (3, 4)


In [54]:
l=[[[[ [10,20,30,40],
    [1,2,3,4],
    ['A','B','C','D']
    ],
    [ [10,20,30,40],
    [1,2,3,4],
    ['A','B','C','D']
    ],
    [ [10,20,30,40],
    [1,2,3,4],
    ['A','B','C','D']
    ]
   ]]]
arr2=np.array([l1])
print(f'array :\n{arr2}')
print(f'array length : {len(arr2)}')
print(f'array dimension : {arr2.ndim}')
print(f'array shape : {arr2.shape}') # (rows,columns)

array :
[[10 20 30 40]]
array length : 1
array dimension : 2
array shape : (1, 4)


In [66]:
l=[[ [10,20,30,40],
    [1,2,3,4],
    ['A','B','C','D'],
    ['W','X','Y','Z']
    ],
     [[10,20,30,40],
    [1,2,3,4],
    ['A','B','C','D'],
     ['W','X','Y','Z']
     ],
    [ [10,20,30,40],
    [1,2,3,4],
    ['A','B','C','D'],
     ['W','X','Y','Z']
    ]
   ]
arr2=np.array([l])
print(f'array :\n{arr2}')
print(f'\narray shape : {arr2.shape}') # (rows,columns)

array :
[[[['10' '20' '30' '40']
   ['1' '2' '3' '4']
   ['A' 'B' 'C' 'D']
   ['W' 'X' 'Y' 'Z']]

  [['10' '20' '30' '40']
   ['1' '2' '3' '4']
   ['A' 'B' 'C' 'D']
   ['W' 'X' 'Y' 'Z']]

  [['10' '20' '30' '40']
   ['1' '2' '3' '4']
   ['A' 'B' 'C' 'D']
   ['W' 'X' 'Y' 'Z']]]]

array shape : (1, 3, 4, 4)


In [77]:
l=[[ [10,20,30,40],
    [1,2,3,4],
    ['A','B','C','D']
    ],
     [[10,20,30,40],
    [1,2,3,4],
    ['A','B','C','D']
     ]
    ]
   
arr2=np.array([l])
print(f'array :\n{arr2}')
print(f'\narray shape : {arr2.shape}') # (rows,columns)

array :
[[[['10' '20' '30' '40']
   ['1' '2' '3' '4']
   ['A' 'B' 'C' 'D']]

  [['10' '20' '30' '40']
   ['1' '2' '3' '4']
   ['A' 'B' 'C' 'D']]]]

array shape : (1, 2, 3, 4)


In [40]:
l=[[[[0,1,2,3,4],
   [5,6,7,8,9],
   [10,11,12,13,14],
   [15,16,17,18,19]],

  [[20,21,22,23,24],
   [25,26,27,28,29],
   [30,31,32,33,34],
   [35,36,37,38,39]],

  [[40,41,42,43,44],
   [45,46,47,48,49],
   [50,51,52,53,54],
   [55,56,57,58,59]]],


 [[[60,61,62,63,64],
   [65,66,67,68,69],
   [70,71,72,73,74],
   [75,76,77,78,79]],

  [[80,81,82,83,84],
   [85,86,87,88,89],
   [90,91,92,93,94],
   [95,96,97,98,99]],

  [[100,101,102,103,104],
   [105,106,107,108,109],
   [110,111,112,113,114],
   [115,116,117,118,119]]]]

arr2=np.array([l])
print(f'array :\n{arr2}')
print(f'\narray shape : {arr2.shape}')

array :
[[[[[  0   1   2   3   4]
    [  5   6   7   8   9]
    [ 10  11  12  13  14]
    [ 15  16  17  18  19]]

   [[ 20  21  22  23  24]
    [ 25  26  27  28  29]
    [ 30  31  32  33  34]
    [ 35  36  37  38  39]]

   [[ 40  41  42  43  44]
    [ 45  46  47  48  49]
    [ 50  51  52  53  54]
    [ 55  56  57  58  59]]]


  [[[ 60  61  62  63  64]
    [ 65  66  67  68  69]
    [ 70  71  72  73  74]
    [ 75  76  77  78  79]]

   [[ 80  81  82  83  84]
    [ 85  86  87  88  89]
    [ 90  91  92  93  94]
    [ 95  96  97  98  99]]

   [[100 101 102 103 104]
    [105 106 107 108 109]
    [110 111 112 113 114]
    [115 116 117 118 119]]]]]

array shape : (1, 2, 3, 4, 5)


In [5]:
l=[[[[0,1,2,3,4]
   [5,6,7,8,9]
   [10,11,12,13,14]
   [15,16,17,18,19]]

  [[20,21,22,23,24]
   [25,26,27,28,29]
   [30,31,32,33,34]
   [35,36,37,38,39]]

  [[40,  41,  42,  43,  44]
  [45,  46,  47,  48,  49]
  [50,  51,  52,  53,  54]
  [55,  56,  57,  58,  59]]]]

   
arr2=np.array([l])
print(f'array :\n{arr2}')
print(f'\narray shape : {arr2.shape}') # (rows,columns)

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:6: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:11: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:6: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:11: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\TSTRANSCO\AppData\Local\Temp\ipykernel_11832\2572597580.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  l=[[[[0,1,2,3,4]
C:\Users\TSTRANSCO\AppData\Local\Temp\ipykernel_11832\2572597580.py:6: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [[20,21,22,23,24]
C:\Users\TSTRANSCO\Ap

TypeError: list indices must be integers or slices, not tuple

In [30]:
l=[[[[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]],

      [[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]],

      [[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]]]]

arr2=np.array([l])
print(f'array :\n{arr2}')
print(f'\narray shape : {arr2.shape}') # (rows,columns)

array :
[[[[[ 0  1  2  3  4]
    [ 5  6  7  8  9]
    [10 11 12 13 14]
    [15 16 17 18 19]]

   [[20 21 22 23 24]
    [25 26 27 28 29]
    [30 31 32 33 34]
    [35 36 37 38 39]]

   [[40 41 42 43 44]
    [45 46 47 48 49]
    [50 51 52 53 54]
    [55 56 57 58 59]]]]]

array shape : (1, 1, 3, 4, 5)


In [ ]:
Array shapes:

(2,3,4,5)
(5,4,3,2,1)

In [ ]:
array shape : (2,3,4,5)

In [32]:
import numpy as np

# Original list with 60 elements
l = [[[[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]],

      [[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]],

      [[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]]]]

# Step 1: Flatten
flat = np.array(l).flatten()

# Step 2: Add 60 more elements to get to 120
needed = 120 - flat.size
extra = np.arange(flat.max() + 1, flat.max() + 1 + needed)
full_data = np.concatenate([flat, extra])

# Step 3: Reshape to (2, 3, 4, 5)
arr2 = full_data.reshape((2, 3, 4, 5))

# Output
print(f'array :\n{arr2}')
print(f'\narray shape : {arr2.shape}')  # Should be (2, 3, 4, 5)

array :
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]

array shape : (2, 3, 4, 5)


In [ ]:
array shape : (5,4,3,2,1)